name: Deploy to HuggingFace

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add huggingface https://AhmadDurrani:${HF_TOKEN}@huggingface.co/spaces/AhmadDurrani/food-mind
          git push huggingface main --force